export const listaProfessores = [
    { nome: "Adriana Aparecida Guimaraes", email: "adriana@utfpr.edu.br" },
    { nome: "Ana Maria Bueno", email: "anam@utfpr.edu.br" },
    { nome: "Ana Paula Milanez", email: "apmilanez@utfpr.edu.br" },
    { nome: "Antonio Augusto De Paula Xavier", email: "augustox@utfpr.edu.br" },
    { nome: "Ariel Orlei Michaloski", email: "ariel@utfpr.edu.br" },
    { nome: "Augusto Foronda", email: "foronda@utfpr.edu.br" },
    { nome: "Carla Cristiane Sokulski", email: "carlac@utfpr.edu.br" },
    { nome: "Cristiane Galvao Fidelis", email: "fidelis@utfpr.edu.br" },
    { nome: "Cristiane Toniolo Dias", email: "cristianetdias@utfpr.edu.br" },
    { nome: "Daniel Poletto Tesser", email: "danieltesser@utfpr.edu.br" },
    { nome: "David Alexander Chipana Mollinedo", email: "davida@utfpr.edu.br" },
    { nome: "Diego Roberto Antunes", email: "drantunes@utfpr.edu.br" },
    { nome: "Edilson Giffhorn", email: "edilsongiffhorn@utfpr.edu.br" },
    { nome: "Ednei Felix Reis", email: "edneif@utfpr.edu.br" },
    { nome: "Edson Jacinski", email: "jacinski@utfpr.edu.br" },
    { nome: "Eliana Claudia Mayumi Ishikawa", email: "eishikawa@utfpr.edu.br" },
    { nome: "Eloiza Aparecida Silva Avila De Matos", email: "elomatos@utfpr.edu.br" },
    { nome: "Everton Luiz De Melo", email: "evertonmelo@utfpr.edu.br" },
    { nome: "Fabio Jose Ceron Branco", email: "fbranco@utfpr.edu.br" },
    { nome: "Fabio Neves Puglieri", email: "puglieri@utfpr.edu.br" },
    { nome: "Fernanda Tavares Treinta", email: "fernandatreinta@utfpr.edu.br" },
    { nome: "Flavio Madalosso Vieira", email: "flaviovieira@utfpr.edu.br" },
    { nome: "Geraldo Ranthum", email: "granthum@utfpr.edu.br" },
    { nome: "Helyane Bronoski Borges", email: "helyane@utfpr.edu.br" },
    { nome: "Hercules Alves De Oliveira Junior", email: "hercules@utfpr.edu.br" },
    { nome: "Iara Da Cunha Ribeiro Da Silva", email: "iarasilva@utfpr.edu.br" },
    { nome: "Jose Alves De Faria Filho", email: "faria@utfpr.edu.br" },
    { nome: "Joseane Pontes", email: "joseane@utfpr.edu.br" },
    { nome: "Juan Carlos Claros Garcia", email: "jcgarcia@utfpr.edu.br" },
    { nome: "Katya Cristina De Lima Picanco", email: "katyapicanco@utfpr.edu.br" },
    { nome: "Lourival Aparecido De Gois", email: "gois@utfpr.edu.br" },
    { nome: "Luiz Andre Brito Coelho", email: "lacoelho@utfpr.edu.br" },
    { nome: "Luiz Rafael Schmitke", email: "luizr@utfpr.edu.br" },
    { nome: "Marcia De Andrade Pereira Bernardinis", email: "marciabernardinis@utfpr.edu.br" },
    { nome: "Marcos Cesar Verges", email: "mcverges@utfpr.edu.br" },
    { nome: "Marcos Tadeu Andrade Cordeiro", email: "marcoscordeiro@utfpr.edu.br" },
    { nome: "Maria Claudia Aguitoni", email: "mcaguitoni@utfpr.edu.br" },
    { nome: "Nelson Ari Canabarro De Oliveira", email: "canabarro@utfpr.edu.br" },
    { nome: "Nilceia Aparecida Maciel Pinheiro", email: "nilceia@utfpr.edu.br" },
    { nome: "Rafael Ribaski Borges", email: "rafaelrborges@utfpr.edu.br" },
    { nome: "Regina Negri Pagani", email: "reginapagani@utfpr.edu.br" },
    { nome: "Reginaldo De Oliveira", email: "reoliveira@utfpr.edu.br" },
    { nome: "Richard Duarte Ribeiro", email: "richardribeiro@utfpr.edu.br" },
    { nome: "Rogerio Ranthum", email: "ranthum@utfpr.edu.br" },
    { nome: "Rui Tadashi Yoshino", email: "ruiyoshino@utfpr.edu.br" },
    { nome: "Sani De Carvalho Rutz Da Silva", email: "sani@utfpr.edu.br" }
  ];
  